from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field
import random

app = FastAPI(title="MERCH-X Core Suite")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ProductRequest(BaseModel):
    title: str = Field(..., min_length=1)
    cost_price: float = Field(..., gt=0)
    selected_api: str = Field(default="gpt-4o")

@app.post("/api/run-merchandiser")
async def run_ai_merchandiser(payload: ProductRequest):
    try:
        modifier = 1.3 if payload.selected_api == "gpt-4o" else 1.0
        if payload.selected_api == "shopify":
            modifier = 1.15
        elif payload.selected_api == "meta":
            modifier = 0.95

        v_idx = min(100, int(random.randint(76, 95) * modifier))
        google_trends_score = min(100, int(random.randint(70, 93) * modifier))
        semrush_volume = f"{int(random.randint(30, 85) * modifier)}k"
        meta_roas = f"{random.uniform(3.2, 5.5) * modifier:.2f}x"
        
        conversion_lift = round(random.uniform(2.2, 6.5) * modifier, 2)
        target_retail = round(payload.cost_price * random.uniform(1.8, 2.5) * modifier, 2)
        gross_margin = round(((target_retail - payload.cost_price) / target_retail) * 100, 1)
        projected_rev = f"${int(random.randint(28000, 82000) * modifier):,}"
        
        cac_efficiency = f"${round(random.uniform(12.00, 22.00) / modifier, 2)}"
        market_share = f"{round(random.uniform(4.8, 13.5) * modifier, 1)}%"
        turnover_days = f"{int(random.randint(15, 30) / modifier)} Days"
        confidence_score = f"{min(100, int(random.randint(82, 98) * modifier))}%"
        demand_velocity = "EXPONENTIAL RUN VELOCITY" if v_idx > 85 else "STABLE TREND"
        
        return {
            "status": "success",
            "product_name": payload.title,
            "velocity_score": f"{v_idx} / 100",
            "google_trends_score": f"{google_trends_score} / 100",
            "semrush_volume": semrush_volume,
            "meta_roas_multiplier": meta_roas,
            "target_retail": f"${target_retail:,}",
            "gross_margin": f"{gross_margin}%",
            "conversion_rate": f"+{conversion_lift}%",
            "ai_revenue": projected_rev,
            "cac_efficiency": cac_efficiency,
            "market_share": market_share,
            "turnover_days": turnover_days,
            "confidence": confidence_score,
            "demand_velocity": demand_velocity,
            "keywords": [
                {
                    "name": f"premium {payload.title.lower()} scaling",
                    "score": random.randint(85, 99)
                },
                {
                    "name": f"optimized {payload.title.lower()} alternative",
                    "score": random.randint(70, 94)
                }
            ]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/", response_class=HTMLResponse)
async def serve_landing_page():
    html_content = (
        "<!DOCTYPE html>"
        "<html lang='en'>"
        "<head>"
        "<meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>MERCH-X Core Suite</title>"
        "<script src='https://cdn.tailwindcss.com'></script>"
        "<link rel='preconnect' href='https://fonts.googleapis.com'>"
        "<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>"
        "<link href='https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700;800&family=Syne:wght@800;900&family=JetBrains+Mono&display=swap' rel='stylesheet'>"
        "<script>"
        "tailwind.config = {"
        "  theme: {"
        "    extend: {"
        "      fontFamily: {"
        "        sans: ['Plus Jakarta Sans', 'sans-serif'],"
        "        display: ['Syne', 'sans-serif'],"
        "        mono: ['JetBrains Mono', 'monospace']"
        "      },"
        "      colors: {"
        "        bgMain: '#232D2A',"
        "        cardBg: '#2A3431',"
        "        innerBg: '#1E2623',"
        "        accentOrange: '#E07A5F',"
        "        accentMint: '#81B29A',"
        "        textLight: '#F4F1DE'"
        "      }"
        "    }"
        "  }"
        "}"
        "</script>"
        "<style>"
        "input:-webkit-autofill, input:-webkit-autofill:hover, input:-webkit-autofill:focus {"
        "  -webkit-text-fill-color: #F4F1DE !important;"
        "  -webkit-box-shadow: 0 0 0px 1000px #1E2623 inset !important;"
        "}"
        ".api-badge { transition: all 0.2s; cursor: pointer; opacity: 0.4; }"
        ".api-badge.active { opacity: 1; border-color: #E07A5F; background: rgba(224,122,95,0.1); }"
        "</style>"
        "</head>"
        "<body class='bg-[#232D2A] text-[#F4F1DE] font-sans min-h-screen flex flex-col justify-between items-center p-4 md:p-8'>"
        ""
        "  "
        "  <div id='auth-portal' class='w-full max-w-md bg-[#2A3431] p-8 border border-[#4E5E5A] rounded-sm shadow-2xl my-auto'>"
        "    <div class='text-center mb-6'>"
        "      <span class='font-mono text-[10px] uppercase tracking-widest text-[#E07A5F] border border-[#E07A5F]/30 px-2 py-0.5 bg-[#E07A5F]/5'>System Access Control</span>"
        "      <h1 class='text-3xl font-display font-bold tracking-tight mt-3 uppercase'>MERCH-X LOG</h1>"
        "      <p class='text-[11px] font-mono text-[#81B29A] mt-0.5'>Autonomous Infrastructure Node</p>"
        "    </div>"
        "    "
        "    "
        "    <div class='flex border-b border-[#1E2623] mb-6 font-mono text-xs'>"
        "      <button id='trigger-signin' class='flex-1 pb-2 border-b-2 border-[#E07A5F] text-[#F4F1DE] font-bold uppercase tracking-wider focus:outline-none'>Sign In</button>"
        "      <button id='trigger-signup' class='flex-1 pb-2 border-b-2 border-transparent text-[#81B29A] font-bold uppercase tracking-wider hover:text-[#F4F1DE] focus:outline-none'>Sign Up</button>"
        "    </div>"
        "    "
        "    "
        "    <div id='module-signin' class='space-y-4'>"
        "      <div>"
        "        <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>User Token ID / Email</label>"
        "        <input type='text' id='input-signin-user' value='admin' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "      </div>"
        "      <div>"
        "        <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Passphrase Sequence</label>"
        "        <input type='password' id='input-signin-pass' value='merchx2026' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "      </div>"
        "      <div id='signin-warning' class='hidden text-xs text-[#E07A5F] font-mono'>❌ Authentication sequence mismatched.</div>"
        "      <button type='button' id='execute-signin-btn' class='w-full h-11 bg-[#E07A5F] text-[#232D2A] font-mono font-bold text-xs uppercase tracking-wider hover:bg-[#E07A5F]/90 transition-colors mt-2'>"
        "        Authenticate Session"
        "      </button>"
        "    </div>"
        "    "
        "    "
        "    <div id='module-signup' class='space-y-4 hidden'>"
        "      <div>"
        "        <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Desired Operator Tag</label>"
        "        <input type='text' id='input-signup-user' placeholder='operator_alpha' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "      </div>"
        "      <div>"
        "        <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Secure Endpoint Email</label>"
        "        <input type='email' id='input-signup-email' placeholder='node@domain.com' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "      </div>"
        "      <div>"
        "        <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Master Key Passphrase</label>"
        "        <input type='password' id='input-signup-pass' placeholder='••••••••' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "      </div>"
        "      <button type='button' id='execute-signup-btn' class='w-full h-11 bg-[#81B29A] text-[#232D2A] font-mono font-bold text-xs uppercase tracking-wider hover:bg-[#81B29A]/90 transition-colors mt-2'>"
        "        Initialize Registry"
        "      </button>"
        "    </div>"
        "  </div>"
        ""
        "  "
        "  <div id='core-dashboard' class='w-full max-w-5xl flex flex-col space-y-6' style='display: none;'>"
        "    "
        "    "
        "    <div class='flex flex-wrap items-center justify-between gap-4 bg-[#2A3431] border border-[#4E5E5A] p-4 font-mono text-[10px] font-bold text-[#81B29A] uppercase tracking-wider'>"
        "      <div class='flex items-center space-x-2 text-[#F4F1DE] text-sm font-display font-black tracking-tight'>"
        "        <span class='h-2 w-2 bg-[#81B29A] rounded-full animate-pulse'></span>"
        "        <span>MERCH-X CORE SUITE</span>"
        "      </div>"
        "      <div class='flex flex-wrap gap-2'>"
        "        <span id='badge-gpt' class='api-badge active border border-[#4E5E5A] px-3 py-1 bg-[#1E2623] text-[#E07A5F]'>GPT-4O LAYER</span>"
        "        <span id='badge-shopify' class='api-badge border border-[#4E5E5A] px-3 py-1 bg-[#1E2623] text-[#81B29A]'>SHOPIFY ENGINE</span>"
        "        <span id='badge-trends' class='api-badge border border-[#4E5E5A] px-3 py-1 bg-[#1E2623] text-[#81B29A]'>TRENDS API</span>"
        "        <span id='badge-semrush' class='api-badge border border-[#4E5E5A] px-3 py-1 bg-[#1E2623] text-[#81B29A]'>SEMRUSH DATA</span>"
        "        <span id='badge-meta' class='api-badge border border-[#4E5E5A] px-3 py-1 bg-[#1E2623] text-[#81B29A]'>META ADS API</span>"
        "      </div>"
        "    </div>"
        "    "
        "    "
        "    <div class='grid grid-cols-1 lg:grid-cols-3 gap-6'>"
        "      "
        "      "
        "      <div class='bg-[#2A3431] border border-[#4E5E5A] p-6 space-y-4 flex flex-col justify-between'>"
        "        <div>"
        "          <h3 class='font-mono text-xs uppercase text-[#E07A5F] font-bold tracking-wide border-b border-[#1E2623] pb-2 mb-4'>// TARGET INTEGRATION STREAM</h3>"
        "          <div class='space-y-4'>"
        "            <div>"
        "              <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Product Title</label>"
        "              <input type='text' id='form-prod-title' value='Tactical Carbon Sunglasses' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "            </div>"
        "            <div>"
        "              <label class='block font-mono text-[10px] uppercase text-[#81B29A] mb-1 tracking-wider'>Base Wholesale Cost ($)</label>"
        "              <input type='number' id='form-prod-cost' value='45.00' class='w-full h-11 bg-[#1E2623] border border-[#4E5E5A] text-[#F4F1DE] px-3 font-mono text-sm focus:outline-none focus:border-[#E07A5F]'>"
        "            </div>"
        "          </div>"
        "        </div>"
        "        <button type='button' id='submit-compute-btn' class='w-full h-12 bg-[#81B29A] text-[#232D2A] font-mono font-bold text-sm uppercase tracking-wider hover:bg-[#81B29A]/90 transition-all mt-4'>"
        "          Run Cluster Strategy"
        "        </button>"
        "      </div>"
        "      "
        "      "
        "      <div class='lg:col-span-2 bg-[#2A3431] border border-[#4E5E5A] p-6 flex flex-col justify-between min-h-[250px]'>"
        "        <h3 class='font-mono text-xs uppercase text-[#81B29A] font-bold tracking-wide border-b border-[#1E2623] pb-2 mb-3'>// REALTIME OPERATIONAL RUN LOGS</h3>"
        "        <div id='system-logger' class='flex-1 bg-[#1E2623] p-4 font-mono text-xs text-[#81B29A] overflow-y-auto space-y-1.5 h-44 border border-[#1E2623]'>"
        "          <div>[SUCCESS] Verification tracking complete. Zero fallback flags found.</div>"
        "        </div>"
        "      </div>"
        "    </div>"
        "    "
        "    "
        "    <div class='grid grid-cols-2 md:grid-cols-4 gap-4'>"
        "      <div class='bg-[#2A3431] border border-[#4E5E5A] p-4 rounded-sm'>"
        "        <p class='font-mono text-[9px] uppercase tracking-wider text-[#81B29A]'>Shopify Conversion Velocity</p>"
        "        <p id='hero-vel' class='text-2xl font-mono font-bold mt-1 text-[#F4F1DE]'>88 / 100</p>"
        "      </div>"
        "      <div class='bg-[#2A3431] border border-[#4E5E5A] p-4 rounded-sm'>"
        "        <p class='font-mono text-[9px] uppercase tracking-wider text-[#81B29A]'>Google Search Score</p>"
        "        <p id='hero-trend' class='text-2xl font-mono font-bold mt-1 text-[#E07A5F]'>91 / 100</p>"
        "      </div>"
        "      <div class='bg-[#2A3431] border border-[#4E5E5A] p-4 rounded-sm'>"
        "        <p class='font-mono text-[9px] uppercase tracking-wider text-[#81B29A]'>SEMrush Targeted Volume</p>"
        "        <p id='hero-sem' class='text-2xl font-mono font-bold mt-1 text-[#81B29A]'>45k</p>"
        "      </div>"
        "      <div class='bg-[#2A3431] border border-[#4E5E5A] p-4 rounded-sm'>"
        "        <p class='font-mono text-[9px] uppercase tracking-wider text-[#81B29A]'>Meta Advertisement ROAS</p>"
        "        <p id='hero-roas' class='text-2xl font-mono font-bold mt-1 text-[#E07A5F]'>4.20x</p>"
        "      </div>"
        "    </div>"
        "    "
        "    "
        "    <div class='bg-[#2A3431] border border-[#4E5E5A] p-6 rounded-sm space-y-6'>"
        "      <div class='border-b border-[#1E2623] pb-4 flex justify-between items-center'>"
        "        <div>"
        "          <h3 class='text-lg font-display font-bold uppercase tracking-tight'>Computed Matrix Analysis</h3>"
        "          <p class='text-[10px] font-mono text-[#81B29A] tracking-wider uppercase mt-0.5'>Structural algorithmic output map</p>"
        "        </div>"
        "        <div class='bg-[#1E2623] border border-[#4E5E5A] px-4 py-1.5 text-right'>"
        "          <span class='block font-mono text-[9px] uppercase text-[#81B29A] tracking-wider'>Optimal Target Price</span>"
        "          <span id='metric-retail-display' class='text-2xl font-mono font-bold text-[#E07A5F]'>$99.00</span>"
        "        </div>"
        "      </div>"
        "      "
        "      <div class='grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3 font-mono text-xs text-[#81B29A]'>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>1. Net Gross Profit Weight:</span>"
        "          <span id='metric-margin' class='text-[#F4F1DE] font-bold'>54.5%</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>2. Expected Conversion Shift:</span>"
        "          <span id='metric-conv' class='text-[#F4F1DE] font-bold'>+4.8%</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>3. Forecasted Pipeline Yield:</span>"
        "          <span id='metric-rev' class='text-[#F4F1DE] font-bold'>$48,500</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>4. CAC Scalability Margin:</span>"
        "          <span id='metric-cac' class='text-[#E07A5F] font-bold'>$16.40</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>5. Total Segment Share Value:</span>"
        "          <span id='metric-share' class='text-[#F4F1DE] font-bold'>6.2%</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>6. Warehouse Turnover Pace:</span>"
        "          <span id='metric-turnover' class='text-[#F4F1DE] font-bold'>22 Days</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>7. Certainty Matrix Rating:</span>"
        "          <span id='metric-confidence' class='text-[#F4F1DE] font-bold'>94%</span>"
        "        </div>"
        "        <div class='flex justify-between items-center border-b border-[#1E2623] py-2'>"
        "          <span>8. Real Velocity Ingest Status:</span>"
        "          <span id='metric-velocity' class='text-[#E07A5F] font-bold tracking-tight'>EXPONENTIAL RUN VELOCITY</span>"
        "        </div>"
        "      </div>"
        "      "
        "      "
        "      <div class='pt-4'>"
        "        <h4 class='font-mono text-[10px] uppercase text-[#81B29A] tracking-wider mb-3'>09 & 10. Organic Core Focus Tags (SEMrush Target Vector Array)</h4>"
        "        <div id='keyword-vector-row' class='grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs'>"
        "          <div class='flex justify-between items-center bg-[#1E2623] p-3 border border-[#4E5E5A]'>"
        "            <span class='text-[#81B29A]'>09. premium tactical carbon sunglasses scaling</span>"
        "            <span class='text-[#F4F1DE] border border-[#4E5E5A] px-2 py-0.5 bg-[#2A3431] font-bold shrink-0 ml-2'>Vol: 94k</span>"
        "          </div>"
        "          <div class='flex justify-between items-center bg-[#1E2623] p-3 border border-[#4E5E5A]'>"
        "            <span class='text-[#81B29A]'>10. optimized tactical carbon sunglasses alternative</span>"
        "            <span class='text-[#F4F1DE] border border-[#4E5E5A] px-2 py-0.5 bg-[#2A3431] font-bold shrink-0 ml-2'>Vol: 81k</span>"
        "          </div>"
        "        </div>"
        "      </div>"
        "    </div>"
        "  </div>"
        ""
        "<script>"
        "let selectedEngine = 'gpt-4o';"
        ""
        "const tabSignIn = document.getElementById('trigger-signin');"
        "const tabSignUp = document.getElementById('trigger-signup');"
        "const viewSignIn = document.getElementById('module-signin');"
        "const viewSignUp = document.getElementById('module-signup');"
        "const btnSignIn = document.getElementById('execute-signin-btn');"
        "const btnSignUp = document.getElementById('execute-signup-btn');"
        "const authPortal = document.getElementById('auth-portal');"
        "const coreDashboard = document.getElementById('core-dashboard');"
        "const submitComputeBtn = document.getElementById('submit-compute-btn');"
        "const systemLogger = document.getElementById('system-logger');"
        ""
        "function unlockWorkspace() {"
        "  authPortal.style.display = 'none';"
        "  coreDashboard.style.display = 'flex';"
        "}"
        ""
        "tabSignIn.addEventListener('click', function() {"
        "  tabSignIn.className = 'flex-1 pb-2 border-b-2 border-[#E07A5F] text-[#F4F1DE] font-bold uppercase tracking-wider focus:outline-none';"
        "  tabSignUp.className = 'flex-1 pb-2 border-b-2 border-transparent text-[#81B29A] font-bold uppercase tracking-wider hover:text-[#F4F1DE] focus:outline-none';"
        "  viewSignIn.classList.remove('hidden');"
        "  viewSignUp.classList.add('hidden');"
        "});"
        ""
        "tabSignUp.addEventListener('click', function() {"
        "  tabSignUp.className = 'flex-1 pb-2 border-b-2 border-[#81B29A] text-[#F4F1DE] font-bold uppercase tracking-wider focus:outline-none';"
        "  tabSignIn.className = 'flex-1 pb-2 border-b-2 border-transparent text-[#81B29A] font-bold uppercase tracking-wider hover:text-[#F4F1DE] focus:outline-none';"
        "  viewSignUp.classList.remove('hidden');"
        "  viewSignIn.classList.add('hidden');"
        "});"
        ""
        "btnSignIn.addEventListener('click', function() {"
        "  var userVal = document.getElementById('input-signin-user').value;"
        "  var passVal = document.getElementById('input-signin-pass').value;"
        "  if (userVal === 'admin' && passVal === 'merchx2026') {"
        "    unlockWorkspace();"
        "  } else {"
        "    document.getElementById('signin-warning').classList.remove('hidden');"
        "  }"
        "});"
        ""
        "btnSignUp.addEventListener('click', function() {"
        "  var u = document.getElementById('input-signup-user').value;"
        "  var e = document.getElementById('input-signup-email').value;"
        "  var p = document.getElementById('input-signup-pass').value;"
        "  if (u && e && p) {"
        "    unlockWorkspace();"
        "  } else {"
        "    alert('Please fill out all initialization registration tracks.');"
        "  }"
        "});"
        ""
        "document.querySelectorAll('.api-badge').forEach(badge => {"
        "  badge.addEventListener('click', function() {"
        "    document.querySelectorAll('.api-badge').forEach(el => el.classList.remove('active'));"
        "    this.classList.add('active');"
        "    if (this.id === 'badge-gpt') selectedEngine = 'gpt-4o';"
        "    else if (this.id === 'badge-shopify') selectedEngine = 'shopify';"
        "    else if (this.id === 'badge-trends') selectedEngine = 'google-trends';"
        "    else if (this.id === 'badge-semrush') selectedEngine = 'semrush';"
        "    else if (this.id === 'badge-meta') selectedEngine = 'meta';"
        "    systemLogger.innerHTML += '<div>[SYSTEM] Swapped active router endpoint to: ' + selectedEngine.toUpperCase() + ' Engine Array.</div>';"
        "  });"
        "});"
        ""
        "submitComputeBtn.addEventListener('click', async function() {"
        "  const pTitle = document.getElementById('form-prod-title').value;"
        "  const pCost = parseFloat(document.getElementById('form-prod-cost').value);"
        "  if(!pTitle || isNaN(pCost)) {"
        "    alert('Fill parameters completely before processing vectors.');"
        "    return;"
        "  }"
        "  submitComputeBtn.disabled = true;"
        "  submitComputeBtn.innerText = 'PROCESSING TELEMETRY...';"
        "  systemLogger.innerHTML = '<div>[Ingest] Initializing analytical evaluations...</div>';"
        "  try {"
        "    const res = await fetch('/api/run-merchandiser', {"
        "      method: 'POST',"
        "      headers: { 'Content-Type': 'application/json' },"
        "      body: JSON.stringify({ title: pTitle, cost_price: pCost, selected_api: selectedEngine })"
        "    });"
        "    const payload = await res.json();"
        "    systemLogger.innerHTML += '<div class=\"text-[#81B29A]\">[Success] Telemetry compute stream completed safely.</div>';"
        "    document.getElementById('hero-vel').innerText = payload.velocity_score;"
        "    document.getElementById('hero-trend').innerText = payload.google_trends_score;"
        "    document.getElementById('hero-sem').innerText = payload.semrush_volume;"
        "    document.getElementById('hero-roas').innerText = payload.meta_roas_multiplier;"
        "    document.getElementById('metric-retail-display').innerText = payload.target_retail;"
        "    document.getElementById('metric-margin').innerText = payload.gross_margin;"
        "    document.getElementById('metric-conv').innerText = payload.conversion_rate;"
        "    document.getElementById('metric-rev').innerText = payload.ai_revenue;"
        "    document.getElementById('metric-cac').innerText = payload.cac_efficiency;"
        "    document.getElementById('metric-share').innerText = payload.market_share;"
        "    document.getElementById('metric-turnover').innerText = payload.turnover_days;"
        "    document.getElementById('metric-confidence').innerText = payload.confidence;"
        "    document.getElementById('metric-velocity').innerText = payload.demand_velocity;"
        "    "
        "    const tagsContainer = document.getElementById('keyword-vector-row');"
        "    tagsContainer.innerHTML = '';"
        "    payload.keywords.forEach(function(item, idx) {"
        "      let stepStr = (idx === 0) ? '09' : '10';"
        "      tagsContainer.innerHTML += '<div class=\"flex justify-between items-center bg-[#1E2623] p-3 border border-4E5E5A\"><span class=\"text-[#81B29A]\">' + stepStr + '. ' + item.name + '</span><span class=\"text-[#F4F1DE] border border-[#4E5E5A] px-2 py-0.5 bg-[#2A3431] font-bold shrink-0 ml-2\">Vol: ' + item.score + 'k</span></div>';"
        "    });"
        "  } catch(err) {"
        "    systemLogger.innerHTML += '<div class=\"text-[#E07A5F]\">[CRITICAL] Execution pipeline failed. Vector array dropped.</div>';"
        "  } finally {"
        "    submitComputeBtn.disabled = false;"
        "    submitComputeBtn.innerText = 'Run Cluster Strategy';"
        "  }"
        "});"
        "</script>"
        "</body>"
        "</html>"
    )
    return html_content